### ISSUE TITLE
Cannot use chests with plugin installed

### ISSUE THREAD

**Issue by ErosionYT** [Xd-pro/PocKit#3]
`[06:54:10.195] [Server thread/CRITICAL]: Error: "Typed property LemoniqPvP\PocKit\libs\muqsit\invmenu\session\network\PlayerNetwork::$queue must not be accessed before initialization" (EXCEPTION) in "plugins/Pockit.phar/src/LemoniqPvP/PocKit/libs/muqsit/invmenu/session/network/PlayerNetwork" at line 124`

**Comment by Xd-pro** [comment]
Fixed in https://poggit.pmmp.io/ci/Xd-pro/PocKit/Pockit/6, please update.
